# IRDS 3D Visualization Configuration
# Edit this file to customize your visualization settings

# Data loading settings
data:
  folder_path: "./data"
  file_pattern: "*.txt"
  has_header: false
  add_metadata: true
  columns: null  # Set to list of column names if needed
  labels_path: "./labels.csv"  # Path to gesture labels CSV file

# Visualization settings
visualization:
  x_cols: null  # Set to [x_col, y_col, z_col] for single point mode
  frame_col: null
  max_rows: 500
  interval_ms: 100
  point_size: 20
  elev: 20
  azim: -60
  save_path: null  # Set to output file path (.gif or .mp4)
  dpi: 100
  show: true

# Skeleton settings (for 25 joints mode)
skeleton:
  enabled: true  # Auto-detected if >=75 numeric columns
  num_joints: 25
  start_col: 0
  order: "xyz"  # Permutation of xyz
  connect: true  # Draw connections between joints to form skeleton

# Filter settings (set to focus on specific data)
filters:
  source_file: null  # e.g., "307_18_4_4_1_sit.txt"
  subject_id: null   # e.g., "307"
  date_id: null      # e.g., "18"
  gesture_label: null # e.g., "4"
  rep_number: null   # e.g., "4"
  correct_label: null # e.g., "1"
  position: null     # e.g., "sit"
