# Example: Visualize a specific file
data:
  folder_path: "./data"
  file_pattern: "202_18_3_2_3_stand.txt"  # Specific file only
  #file_pattern: "101_18_0_1_1_stand.txt"  # Specific file only
  # file_pattern: "214_18_8_1_1_Stand-frame.txt"  # Specific file only
  # file_pattern: "207_18_3_3_2_stand.txt"  # Specific file only

  has_header: false
  add_metadata: true
  max_files: 1  # Ensure only 1 file is loaded

visualization:
  max_rows: 800
  interval_ms: 50
  point_size: 25
  save_path: "single_sequence.mp4"
  show: true

skeleton:
  enabled: true
  num_joints: 25
  connect: true

filters:
  # No additional filters needed since we're loading specific file
