experiment:
  name: "CLIP Gesture Model - Fast Debug"
  description: "Quick training for debugging"

hardware:
  device: "auto"  # auto, cpu, cuda
  num_workers: 4

data:
  folder_path: "data"
  max_files: 10  # Very small for debugging
  sequence_length: 5  # Short sequences
  test_size: 0.2

model:
  input_size: 75  # 25 joints * 3 coordinates
  hidden_size: 128
  num_layers: 2
  dropout: 0.1

training:
  batch_size: 8  # Small batch
  num_epochs: 5  # Very few epochs for debugging
  learning_rate: 0.001
  weight_decay: 0.0001

output:
  model_path: "clip_gesture_model_debug.pth"
  scaler_path: "clip_gesture_scaler_debug.json"
  info_path: "clip_gesture_info_debug.json"
