# Experimental Configuration (Advanced techniques)
# Data augmentation, advanced regularization, ensemble methods

data:
  folder_path: "data"
  max_files: 250                    # Moderate data size
  sequence_length: 25               # Very long sequences
  test_size: 0.2
  random_state: 42

model:
  skeleton_encoder:
    hidden_dim: 256
    num_layers: 4                  # Deeper network
    dropout: 0.4                    # High dropout
    attention_heads: 8
    
  text_encoder:
    embedding_dim: 128
    hidden_dim: 256
    num_layers: 4
    
  clip_model:
    embedding_dim: 256
    logit_scale: 0.03               # Lower temperature

training:
  num_epochs: 200                  # Many epochs
  batch_size: 4                    # Very small batch size
  learning_rate: 0.00005           # Very low learning rate
  
  optimizer: "AdamW"
  weight_decay: 0.05               # High weight decay
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  
  lr_scheduler: "CosineAnnealingWarmRestarts"
  lr_warmup_epochs: 30
  lr_min: 0.000001
  
  contrastive_weight: 0.7
  classification_weight: 0.3
  temperature: 0.03

augmentation:
  enabled: true
  noise_std: 0.02                  # More noise
  rotation_angle: 10               # More rotation
  time_shift: 0.2                  # More time shift
  scale_factor: 0.2                # More scaling

regularization:
  dropout: 0.5                     # Very high dropout
  weight_decay: 0.05               # High weight decay
  gradient_clip: 0.1               # Strong gradient clipping
  early_stopping:
    enabled: true
    patience: 50
    min_delta: 0.0001

output:
  model_save_path: "clip_gesture_model_experimental.pth"
  scaler_save_path: "clip_gesture_scaler_experimental.pkl"
  info_save_path: "clip_gesture_info_experimental.json"
  plots_save_path: "clip_training_curves_experimental.png"
  confusion_matrix_path: "clip_confusion_matrix_experimental.png"

experiment:
  name: "clip_gesture_experimental"
  tags: ["clip", "gesture", "experimental", "rocm"]
  notes: "Experimental CLIP gesture recognition with advanced techniques"
