# Speed Test Configuration
# Minimal data for quick GPU testing

data:
  folder_path: "../data"
  max_files: 20                     # Very small dataset for speed test
  sequence_length: 5                # Very short sequences
  test_size: 0.2
  random_state: 42

model:
  skeleton_encoder:
    hidden_dim: 64                 # Small model
    num_layers: 1
    dropout: 0.1
    attention_heads: 2
    
  text_encoder:
    embedding_dim: 32
    hidden_dim: 64
    num_layers: 1
    
  clip_model:
    embedding_dim: 64
    logit_scale: 0.07

training:
  num_epochs: 5                    # Very few epochs for speed test
  batch_size: 4                    # Small batch size
  learning_rate: 0.001
  
  optimizer: "Adam"
  weight_decay: 0.01
  
  contrastive_weight: 0.5
  classification_weight: 0.5
  temperature: 0.07

augmentation:
  enabled: false                   # No augmentation for speed

regularization:
  dropout: 0.1
  weight_decay: 0.01
  gradient_clip: 1.0
  early_stopping:
    enabled: false                 # No early stopping for speed test

output:
  model_save_path: "outputs/clip_gesture_model_speed_test.pth"
  scaler_save_path: "outputs/clip_gesture_scaler_speed_test.pkl"
  info_save_path: "outputs/clip_gesture_info_speed_test.json"
  plots_save_path: "outputs/clip_training_curves_speed_test.png"
  confusion_matrix_path: "outputs/clip_confusion_matrix_speed_test.png"

experiment:
  name: "clip_gesture_speed_test"
  tags: ["clip", "gesture", "speed_test", "rocm"]
  notes: "Speed test for GPU efficiency"
