# Example: Visualize gesture 4 with skeleton animation
data:
  folder_path: "./data"
  file_pattern: "*.txt"
  has_header: false
  add_metadata: true

visualization:
  max_rows: 600
  interval_ms: 60
  point_size: 30
  save_path: "gesture4_animation.gif"
  show: true

skeleton:
  enabled: true
  num_joints: 25
  connect: true

filters:
  gesture_label: "4"
  position: "sit"
