# Flexible single file configuration - change the filename as needed
data:
  folder_path: "./data"
  file_pattern: "307_18_4_4_1_sit.txt"  # CHANGE THIS to your desired file
  has_header: false
  add_metadata: true
  max_files: 1  # Only load 1 file

visualization:
  max_rows: 600  # All frames from the single file
  interval_ms: 60
  point_size: 30
  show: true

skeleton:
  enabled: true
  num_joints: 25
  connect: true

filters:
  # No filters needed - we're loading specific file
