# Experiment: Large Model (~11M params)
# High capacity for complex patterns

debug:
  level: "Info"
  show_tensor_info: false
  show_memory_usage: true
  show_timing: true

data:
  folder_path: null
  max_files: null
  sequence_length: 20
  test_size: 0.15
  random_state: 42

model:
  architecture: "large"

training:
  num_epochs: 150
  batch_size: 8
  learning_rate: 0.0001
  optimizer: "AdamW"
  weight_decay: 0.01

output:
  model_save_path: "outputs/model_large.pth"
  scaler_save_path: "outputs/scaler_large.json"
  info_save_path: "outputs/info_large.json"
  plots_save_path: "outputs/curves_large.png"
  confusion_matrix_path: "outputs/confusion_large.png"

experiment:
  name: "gesture_large"
  tags: ["large", "11M", "high-capacity"]
  notes: "Large model for complex gesture patterns"

